In [12]:
import torch
from torch.nn import functional as F


In [11]:
a = torch.tril(torch.ones((32, 32)))
a1 = a.masked_fill(a[:32, :32] == 0, float("-inf"))
a2 = a.masked_fill(a == 0, float("-inf"))
torch.allclose(a1, a2)
a1

tensor([[1., -inf, -inf,  ..., -inf, -inf, -inf],
        [1., 1., -inf,  ..., -inf, -inf, -inf],
        [1., 1., 1.,  ..., -inf, -inf, -inf],
        ...,
        [1., 1., 1.,  ..., 1., -inf, -inf],
        [1., 1., 1.,  ..., 1., 1., -inf],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [14]:
F.softmax(a1, dim=-1)

tensor([[1.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0333, 0.0333, 0.0333,  ..., 0.0333, 0.0000, 0.0000],
        [0.0323, 0.0323, 0.0323,  ..., 0.0323, 0.0323, 0.0000],
        [0.0312, 0.0312, 0.0312,  ..., 0.0312, 0.0312, 0.0312]])

In [4]:
q = torch.rand((4, 5, 6))
k = torch.rand((4, 5, 6))

wei = q @ k.transpose(-2, -1)
wei

tensor([[[1.6522, 1.4885, 1.6311, 1.9315, 0.8982],
         [1.9785, 2.0999, 1.8307, 2.4717, 1.5845],
         [1.3366, 1.4140, 1.2336, 1.3855, 0.7809],
         [2.1219, 2.3926, 2.1933, 2.5771, 1.8029],
         [2.3968, 2.8066, 2.4610, 3.1390, 1.9806]],

        [[1.2674, 1.2783, 2.0042, 2.2028, 2.6456],
         [0.9080, 0.6116, 0.9472, 1.3793, 1.4773],
         [1.0587, 1.0621, 1.4441, 1.1501, 0.8855],
         [1.0140, 1.0828, 1.6955, 1.7839, 2.2168],
         [1.2136, 1.0901, 1.5403, 1.3834, 1.0753]],

        [[2.0575, 1.4597, 1.2162, 2.4544, 2.1775],
         [1.7655, 1.6079, 0.7264, 1.8083, 1.5492],
         [1.5115, 1.2542, 1.1582, 1.8516, 1.7144],
         [1.5771, 1.0033, 1.6682, 2.1356, 2.1238],
         [1.6292, 1.0175, 1.4531, 2.2152, 2.0442]],

        [[3.3794, 2.6350, 2.9312, 1.6691, 2.6874],
         [1.8493, 1.3707, 1.4402, 0.6819, 1.6733],
         [2.2960, 1.6580, 1.9057, 1.0005, 2.0123],
         [3.0041, 2.4626, 2.8271, 1.4515, 2.6548],
         [2.5094, 2.3403,